### ISSUE TITLE
beadandó

### ISSUE THREAD

**Issue by meszaros-adam** [Uni-Sopron/fonya-o21-beadando-meszaros-nfa2dfa#1]
@hegyhati 

Jó szerencsét! Nem működik, de nem tudtam ennél jobban megoldani. Elkezdi legenerálni a dfa állapotait, az első még jó is, de a többi már nem.

**Comment by hegyhati** [comment]
- [ ] A readme legyen md formatumban rendesen megformazva, ne txt legyen. Es  a markdown legyen rendesen hasznalva. 
- [ ] A `transitionseparator`-ban a transitions bejaras soran mar torolsz is belole, ez nem szerencses, konnyen felrecsuszhat az ilyen. En inkabb vegigmennek, felepitenek egy uj listat, es utana lecserelnem a kettot. 
- [ ] Ugyanitt a masodik resze a kodnak nem jo, azt pl nem is kezeli normalisan ha modnjuk egy 3 karakteres valami van. 
- [ ] a konvertealas a kezdonel is elcsuszik mar, mert nem veszed az empty lezartat, csak csinalsz egy egy elemu halmazt az NFA kezdoallapotaval, ha jol latom.
- [ ] Szerintem Java-ban is van mar ranged for nem? spok ilyen indexelgetest meg get-elest megusznal vele. 
- [ ] i,j stb helyett beszedesebb nevekkel lehet atlathatobb lenne a kod.
- [ ] a 2. es 3. for (NFA staten, symbol-on) sorrendje nem logikus, forditva lenne jo. Egy adott dfa state-bol (elso for) egy adott szimbolummal (most harmadik) hova lehet elmenni, amihez vegig kell nezni mindegyik nfa state-et (3. for). 
- [ ] Az arraylistedet a hova lehet menni kerdesre nem transition-onkent kelene letrehozni.
- [ ] ugy altalaban en egy cosmo mindent szetbontanek kisebb fuggvenyekre, mert igy nem csoda, ha egy ido utan mar nem latod at.

**Comment by hegyhati** [comment]
@meszike91 Egy issue-nal maradjunk, hogy kovethetok legyenek a dolgok, ne kelljen tobb issue-n ugralni az elozmenyekhez. Bemasolva ide a valaszod:

> A readme-t kijavítottam. A transitionSeparator is úgy működik ahogy kérted és kezeli a kettőnél több betűt is. Ahol tudtam ott próbáltam értelmes nevet adni az iterátoroknak az i j stb... helyett.
> Tényleg nem átlátható. Nem tudom ez jelen állapotban hányast ér, de ha a kettes megvan akkor szerintem hagynám mert ma már sokkal jobbra nem tudnám megcsinálni.

Hat ott indul a dolog, hogy mukodjon. Ha nem mukodik, akkor nincs nagyon mit ertekelni. Nem olyan bonyolult ez az algoritmus, menni fog, tessek kikalapalni.  A pseudo code kb 10 sor, pl:
https://stackoverflow.com/questions/11954935/pseudocode-for-converting-nfa-to-dfa

Szoval menni fog ez, csak ulj le melle es kalapald ki, hogy tenyleg azt csinalja, amit kell. Lepesrol lepesre debuggold ki. Es igen, segitesz magadon, ha ertelmes dolgokat kiszervezel fuggvenybe (pl empty lezartja egy halmaznak, egy adott halmazbol/NFA allapotbol egy szimbolummal hova lehet elmenni, stb) Ha ezek az epitokockak jol megvannak, akkor azokbol tenyleg 10 sorban osszerakhato a teljes konvertalas.

**Comment by meszaros-adam** [comment]
@hegyhati 

Most szerintem alapvetően működik. Kicseréltem a json file-t egy órai példára és és próbáltam szétszedni a dfa-vá alakító függvényt. Viszont a hurok transition-öket nem generálja le most se.

**Comment by meszaros-adam** [comment]
Szerintem sikerült javítani a hurok transition-öket is.

**Comment by hegyhati** [comment]
Na, alakul ez!

`int transitionLetters = multipleTransition.get("with").toString().length();` <-- ehelyett is siman lehetett volna alatt a for-ban ranged forral vegigmenni a karaktereken.

A cikluson belul az if-eket azert inkabb egybe tennek, es a 2., 3/ eset `if else / else` lenne.

`int transitionLetters = multipleTransition.get("with").toString().length();` <--- ezt szerintem nem a cikluson belulre akartad

a fuggveny nevet amugy cserelnem, mert nem adja vissza, hogy mit csinal. Inkabb valami `splitLongTransitions` vagy valami ilyesmi lenne kifejezobb. De mukodesileg rendbenlevonek tunik.

`dfaStateFinder` ez gondolom egy `calculateSimulatedDFAState` vagy ilyesmi. mivel belso fuggveny, nem tennem publicba. 

A fuggveny masodik felet, ami az empty lezartat csinalja, en kitennem egy kulon fuggvenybe, mert logikailag ket kulon dolog. Persze ez meghivhatja azt. De amugy rnedben van. Azert annyi, hogy ugye megint vegigmesz egy ciklussal egy tarolon, amibe kozbe pakolsz. Java most nem tudom pontosan hogy mukodik ilyenkor. Tehat pl azokon is vegigmegy, amiket kozben raktal bele? (Kellene, mert ha vannak tranzitiv empty atmenetek, akkor az meg mindig csak empty ugye)

`ArrayList<Integer> acceptingDfaStates = new ArrayList<Integer>();` <-- ez itt nem `ArrayList<ArrayList<Integer>>` akarna lenni?

Amugy szerintem celszeru lenne type aliasokat bevezetni (gondolom tud olyat a Java (remelem)). Och, ragugliztam, nincs... Java... Csinalhatnal sajat osztalyt, de az nem biztos, hogy megerne. (https://stackoverflow.com/questions/5604390/how-do-i-create-some-variable-type-alias-in-java) mindenesetre egy `class DFAState extends ArrayList<Integer>` -rel siman tudnad roviditeni a kodod, de up to you.

A masik, hogy mindenhol ArrayListet hasznalsz, de amugy egyebkent ugye Neked akar egy Set is jo lenne. 

`dfaConverting` -> `getEquivalentDFA` vagy valami hasonlo. 

`dfaInitialState.add(initialState);` <-- itt is mar meg kellene hivni az Empty lezarast, amit ugye fentebb mondtam, hogy valassz le a transitionrol kulon fuggvenybe. Mert ez nem fog jol mukodni, ha mar a kezdoallapotbol is van empty atmenet.

Az utolso fuggvenyben megint az van, hogy kozben is pakolsz bele a dfa.states-be, mikosben mesz vegig rajta. Nem tudom, mennyire determinisztikus ilyenkor javaban, hogy az ujakat is bedaralja.

De amugy frnako, tenylge kipofoztad, nice!

**Comment by meszaros-adam** [comment]
@hegyhati Kijavítottam a 3 if-et if/else is/else-re. Átneveztem a függvényeket. Külön függvénybe tettem az empty lezárt keresést és lefuttatom a kezdő dfa state-re is.  

`int transitionLetters = multipleTransition.get("with").toString().length(); ` Itt a ciklusban a transition "with" paraméterének a hosszán megyek végig, annyiszor fut le a ciklus ahány karaktert tartalmaz a transition. Nem tudom hogyan tudnám máshogy megoldani. A ranged for-t nem ismerem, nem is tudom van-e ilyen java-ban. Én csak foreach-ről tudok, de azzal se tudom hogy tudnám megoldani. 

> Azert annyi, hogy ugye megint vegigmesz egy ciklussal egy tarolon, amibe kozbe pakolsz. Java most nem tudom pontosan hogy mukodik ilyenkor. Tehat pl azokon is vegigmegy, amiket kozben raktal bele?

A sima for végig megy azokon az elemeken is amiket közben pakoltam bele. A foreach viszont nem, az out of bound exception-t dobot, ezért nem tudtam mindenhol azt használni. 

`ArrayList<Integer> acceptingDfaStates = new ArrayList<Integer>();` Itt csak a dfa state sorszámát mentem el 1-től kezdve. Nem a dfa state-ben lévő nfa state-eket.

**Comment by hegyhati** [comment]
Koszi! ranged for alatt a foreach-re gondoltam, csak midnen nyelven mashogy hivjak. De jo lesz igy akkor. Meg a readme-t pofozd egy kicsit, hogy leirja, mit csinal a program, meg hogyan, meg peldabemenetre milyen peldakimenet, azt grafikusan is megmutatni akkor., ilyesmi. Nem kell hosszan, csak hogyha valaki idetalal, akkor lassa, mirol van szo. Issuet mar lezarom, a readme-t mar nem szandekozom review-zni. Hajra az a zarovizsga felkeszuleshez!
